version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./frontend:/var/www/html
    ports:
      - "8000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASS=
      - DB_NAME=todo_app
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
